"""Validate the unsupervised SRF distance/clustering approach against R.

`UnsupervisedSpatialRandomForest` approximates the original R workflow's
``rfsrc(distance="all")`` unsupervised mode by explicitly training a
classifier to discriminate real vectorised spatial patterns from synthetic
patterns generated by independently permuting each feature column. This
mirrors what `randomForestSRC` documents itself doing internally in
unsupervised mode: it isn't a simplification invented for this package, it's
the same real-vs-synthetic-via-marginal-permutation mechanism, made explicit.

This script tests that claim against real data rather than just asserting
it. It feeds the *exact* vectorised patterns recovered by re-running
`SRFGeoTIFF.R` in R (see `.features/PLAN.md` "Improve Unsupervised SRF
Parity" and `original_source/recovered_from_RData/`) into
`UnsupervisedSpatialRandomForest.fit_prepared`, then compares the resulting
distance matrix and PAM(k=4) clustering against R's own
`myDist.csv`/`pam_k4_clusters.csv`.

Requires `original_source/recovered_from_RData/` (gitignored, not
distributed) to exist -- see `original_source/recovered_from_RData/run_SRFGeoTIFF_bounded.R`
for how to regenerate it.

Run with:

    python examples/validate_unsupervised_srf_distance.py
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

import numpy as np

from spatialized import UnsupervisedSpatialRandomForest

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "original_source" / "recovered_from_RData"

N_CENTERS = 1000
N_ROTATIONS = 4


def main() -> None:
    patterns = _load_csv_matrix(DATA_DIR / "patbase_train.csv")
    assert patterns.shape == (N_CENTERS * N_ROTATIONS, 123), patterns.shape

    r_distance = _load_csv_matrix(DATA_DIR / "myDist.csv")
    assert r_distance.shape == (N_CENTERS, N_CENTERS)

    r_clusters = _load_pam_clusters(DATA_DIR / "pam_k4_clusters.csv")
    assert r_clusters.shape == (N_CENTERS,)

    model = UnsupervisedSpatialRandomForest(n_estimators=100, random_state=20260816, n_jobs=-1)
    model.fit_prepared(patterns, n_centers=N_CENTERS, rotations=True)
    py_distance = model.distance_

    triu = np.triu_indices(N_CENTERS, k=1)
    pearson_r = float(np.corrcoef(py_distance[triu], r_distance[triu])[0, 1])

    from scipy.stats import spearmanr

    spearman_r = float(spearmanr(py_distance[triu], r_distance[triu]).correlation)

    from sklearn.cluster import KMeans
    from sklearn.metrics import adjusted_rand_score

    # Cluster Python's distance matrix the same way R's baseline PAM(k=4)
    # step did (R uses `cluster::pam`; scikit-learn has no PAM, so use
    # k-medoids-like KMeans on an MDS embedding of the distance matrix as a
    # close analogue purely for this comparison).
    from sklearn.manifold import MDS

    embedding = MDS(n_components=8, dissimilarity="precomputed", random_state=42, normalized_stress=False).fit_transform(py_distance)
    py_clusters = KMeans(n_clusters=4, n_init=10, random_state=42).fit_predict(embedding)
    ari = float(adjusted_rand_score(r_clusters, py_clusters))

    summary = {
        "n_centers": N_CENTERS,
        "distance_pearson_r": pearson_r,
        "distance_spearman_r": spearman_r,
        "cluster_adjusted_rand_index": ari,
        "python_distance_range": [float(py_distance.min()), float(py_distance.max())],
        "r_distance_range": [float(r_distance.min()), float(r_distance.max())],
    }
    print(json.dumps(summary, indent=2, sort_keys=True))


def _load_csv_matrix(path: Path) -> np.ndarray:
    with open(path, newline="") as handle:
        reader = csv.reader(handle)
        next(reader)  # header
        rows = [[_parse_float(value) for value in row] for row in reader]
    return np.array(rows, dtype=float)


def _parse_float(value: str) -> float:
    return np.nan if value in ("NA", "") else float(value)


def _load_pam_clusters(path: Path) -> np.ndarray:
    with open(path, newline="") as handle:
        reader = csv.reader(handle)
        next(reader)  # header: sample_index,cluster
        return np.array([int(row[1]) for row in reader], dtype=int)


if __name__ == "__main__":
    main()
