"""Spatial random forest preparation utilities."""

from .encoding import EncodedColumn, PatternEncoder
from .deep_features import (
    DeepFeatureClusteringResult,
    cluster_feature_vectors,
    extract_patches,
    normalize_channels,
    patch_centers,
)
from .models import (
    PredictionBatch,
    SpatialRandomForestClassifier,
    SpatialRandomForestRegressor,
    classification_entropy,
)
from .patterns import (
    FeatureLayout,
    FeatureSpec,
    GridTransform,
    PatternBatch,
    PatternDataset,
    SpatialLayer,
    centers_from_mask,
    centers_from_shape,
    feature_layout,
    grid_from_centers,
    iter_centers,
    iter_pattern_batches,
    pattern_size_from_edge,
    prepare_patterns,
    prepare_training_data,
    vectorize_layer,
    zone_of_influence,
)
from .raster import RasterGrid, read_raster, read_spatial_layer, write_raster
from .unsupervised import (
    ClusterDiagnostics,
    UnsupervisedResult,
    UnsupervisedSpatialRandomForest,
    affinity_from_distance,
    cluster_diagnostics,
    spectral_cluster,
    synthetic_patterns,
)
from .workflows import (
    DomainPrediction,
    GridPrediction,
    TransferPrediction,
    predict_grid,
    predict_grid_to_raster,
    predict_target_proxy_transfer,
    predict_unsupervised_domains,
    train_target_proxy_classifier,
)

__all__ = [
    "EncodedColumn",
    "DeepFeatureClusteringResult",
    "FeatureLayout",
    "FeatureSpec",
    "GridTransform",
    "DomainPrediction",
    "GridPrediction",
    "TransferPrediction",
    "PatternBatch",
    "PatternDataset",
    "PatternEncoder",
    "PredictionBatch",
    "RasterGrid",
    "ClusterDiagnostics",
    "SpatialRandomForestClassifier",
    "SpatialRandomForestRegressor",
    "SpatialLayer",
    "UnsupervisedResult",
    "UnsupervisedSpatialRandomForest",
    "centers_from_mask",
    "centers_from_shape",
    "classification_entropy",
    "affinity_from_distance",
    "cluster_diagnostics",
    "cluster_feature_vectors",
    "extract_patches",
    "feature_layout",
    "grid_from_centers",
    "iter_centers",
    "iter_pattern_batches",
    "normalize_channels",
    "pattern_size_from_edge",
    "patch_centers",
    "prepare_patterns",
    "prepare_training_data",
    "predict_grid",
    "predict_grid_to_raster",
    "predict_target_proxy_transfer",
    "predict_unsupervised_domains",
    "read_raster",
    "read_spatial_layer",
    "spectral_cluster",
    "synthetic_patterns",
    "train_target_proxy_classifier",
    "vectorize_layer",
    "write_raster",
    "zone_of_influence",
]
